title: Eungpyo Jang
description: Environmental Health Researcher focusing on EcoHealth, nature, biodiversity, and human health.
url: "https://eungpyojang.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
future: true
